### ISSUE TITLE
Is there any article that I can learn how to translate?

### ISSUE THREAD

**Issue by felipemarinho97** [raffll/yampt#47]
In your doc you talk about dictionaries, and generating dictionaries.. but I can't understand what they are, and how are.
I want to use some script to extract the strings from the game and then translate everything using the Google Translate API, and so load again into the game files, is it possible?
Also, I'm a experienced programmer and can build such tool.

**Comment by raffll** [comment]
Here, https://www.nexusmods.com/morrowind/mods/44518?tab=files, you have compiled package with an example English-to-Polish base dictionary.

**Comment by raffll** [comment]
> I want to use some script to extract the strings from the game and then translate everything using the Google Translate API, and so load again into the game files, is it possible?

Yes, it's exactly what this program does, but if you want to translate entire game from scratch you need to track all in-game hiperlinks.

**Comment by felipemarinho97** [comment]
> 
> Yes, it's exactly what this program does, but if you want to translate entire game from scratch you need to track all in-game hiperlinks.

Yes, I want to translate entire game.. can you give me some light?
How can I use your tool to extract the strings and then apply the changes again to the game? A dictionary means all extracted string?

**Comment by felipemarinho97** [comment]
Okay, I just generated a dictionary from English to English.. now I can read this file using some script tha access Google Translate API and translate record by record? I think that I'll have to find a way to preserve the "%PCName", "%PCRace"

**Comment by felipemarinho97** [comment]
Your tool extract these hyperlinks to DIAL right? And If I made relationships between these DIAL reacords for each INFO record and populate the with the correct link names?

**Comment by felipemarinho97** [comment]
Okay, I've successful made the tool for translating the INFO records and it's working well. But when I triyed to translate CELL records and tested, the game just brokes.

**Comment by raffll** [comment]
Check "Warnings.txt" in game folder
